# Generated by Django 5.2.5 on 2026-03-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('audio_file', models.FileField(help_text='Upload MP3 / WAV audio file', upload_to='calibration/audios/', verbose_name='Audio File')),
                ('reference_text', models.TextField(help_text='The text seller must read aloud after listening to this audio', verbose_name='Reference Text')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order 1-7', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calibration Audio',
                'verbose_name_plural': 'Calibration Audios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('overall_score', models.FloatField(blank=True, help_text='Average AI score across all attempts (0-100)', null=True, verbose_name='Overall Score')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Calibration Session',
                'verbose_name_plural': 'Calibration Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(help_text="Seller's voice recording for this audio", upload_to='calibration/recordings/', verbose_name='Seller Recording')),
                ('transcribed_text', models.TextField(blank=True, help_text="What Groq Whisper heard from the seller's recording", verbose_name='Transcribed Text')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='Accuracy Score (0-100)')),
                ('fluency_score', models.FloatField(blank=True, null=True, verbose_name='Fluency Score (0-100)')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score (0-100)')),
                ('overall_score', models.FloatField(blank=True, null=True, verbose_name='Overall Score (0-100)')),
                ('ai_feedback', models.JSONField(blank=True, help_text='Full JSON feedback from Groq LLaMA analysis', null=True, verbose_name='AI Detailed Feedback')),
                ('is_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='saler_dashboard.calibrationaudio', verbose_name='Calibration Audio')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='saler_dashboard.calibrationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Calibration Attempt',
                'verbose_name_plural': 'Calibration Attempts',
                'ordering': ['created_at'],
                'unique_together': {('session', 'audio')},
            },
        ),
    ]
