# Generated by Django 5.2.5 on 2026-03-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler_dashboard', '0002_calibrationaudio_calibrationsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationaudio',
            name='reference_text',
        ),
        migrations.CreateModel(
            name='ReferenceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_defficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10, verbose_name='Text Difficulty')),
                ('reference_text', models.TextField(help_text='The text seller must read aloud after listening to this audio', verbose_name='Reference Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_texts', to='saler_dashboard.calibrationaudio', verbose_name='Calibration Audio')),
            ],
            options={
                'verbose_name': 'Reference Text',
                'verbose_name_plural': 'Reference Texts',
                'ordering': ['audio'],
            },
        ),
        migrations.AddField(
            model_name='calibrationattempt',
            name='reference_text',
            field=models.ForeignKey(blank=True, help_text='The specific text the seller was asked to read', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='saler_dashboard.referencetext', verbose_name='Assigned Reference Text'),
        ),
    ]
