# Generated by Django 5.2.5 on 2026-01-25 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_number', models.CharField(help_text="Seller's phone number", max_length=20)),
                ('customer_number', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('twilio_call_sid', models.CharField(blank=True, help_text='Twilio Call SID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the call actually started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the call ended', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total call duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(help_text='Complete JSON report from LLM')),
                ('performance_score', models.IntegerField(blank=True, help_text='Performance score out of 100', null=True)),
                ('call_status', models.CharField(blank=True, help_text='Success/In Progress/Needs Revisit', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='calling.call')),
            ],
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('caller', 'Caller'), ('callee', 'Callee')], max_length=10)),
                ('content', models.TextField(help_text='Transcribed text')),
                ('timestamp', models.CharField(help_text='Timestamp in MM:SS format', max_length=10)),
                ('ai_used_percentage', models.FloatField(blank=True, help_text='Similarity score for caller messages (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='calling.call')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(help_text='AI-generated response suggestion')),
                ('timestamp', models.CharField(help_text='Timestamp in MM:SS format', max_length=10)),
                ('was_used', models.BooleanField(default=False, help_text='Whether caller used this suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='calling.call')),
                ('transcript', models.ForeignKey(blank=True, help_text='The callee message that triggered this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='calling.calltranscript')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['-created_at'], name='calling_cal_created_794d73_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', '-created_at'], name='calling_cal_user_id_a074b3_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['twilio_call_sid'], name='calling_cal_twilio__b470a7_idx'),
        ),
        migrations.AddIndex(
            model_name='calltranscript',
            index=models.Index(fields=['call', 'created_at'], name='calling_cal_call_id_91bffa_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['call', 'created_at'], name='calling_air_call_id_0501e0_idx'),
        ),
    ]
