# Generated by Django 5.2.5 on 2026-01-25 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='user',
            field=models.ForeignKey(
                help_text='User who initiated the call',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calls',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
