# Generated by Django 5.2.5 on 2026-03-12 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorFilterPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Preset Name')),
                ('filter_data', models.JSONField(default=dict, verbose_name='Filter Data')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Preset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_filter_presets', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Auditor Filter Preset',
                'verbose_name_plural': 'Auditor Filter Presets',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_page_size', models.IntegerField(default=20, verbose_name='Default Page Size')),
                ('show_transcripts', models.BooleanField(default=True, verbose_name='Show Call Transcripts')),
                ('show_reports', models.BooleanField(default=True, verbose_name='Show AI Reports')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Email Notifications')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Notification Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_settings', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Auditor Settings',
                'verbose_name_plural': 'Auditor Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditorBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_id', models.IntegerField(verbose_name='Call ID')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Auditor Bookmark',
                'verbose_name_plural': 'Auditor Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'call_id')},
            },
        ),
    ]
