# Generated by Django 5.2.5 on 2026-03-12 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('target_calls', models.IntegerField(default=0, verbose_name='Target Calls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Manager Campaign',
                'verbose_name_plural': 'Manager Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_calls', models.IntegerField(default=0, verbose_name='Target Calls')),
                ('achieved_calls', models.IntegerField(default=0, verbose_name='Achieved Calls')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Target Revenue')),
                ('achieved_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Achieved Revenue')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_targets', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_targets', to='manager_dashboard.managercampaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_targets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Manager Target',
                'verbose_name_plural': 'Manager Targets',
                'ordering': ['-period_end'],
            },
        ),
    ]
