# Generated by Django 5.2.5 on 2026-03-12 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='managertarget',
            constraint=models.UniqueConstraint(fields=('agent', 'period_start', 'period_end'), name='unique_agent_period'),
        ),
    ]
